apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: networking
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/registered
                operator: In
                values:
                - "true"
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
